// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBGOc0m8sW8S23Qdfhz3qJlye_vS-Z26Q',
    appId: '1:519570864839:web:db66dfd278599c83975ce2',
    messagingSenderId: '519570864839',
    projectId: 'brookmate-app-sbu',
    authDomain: 'brookmate-app-sbu.firebaseapp.com',
    storageBucket: 'brookmate-app-sbu.appspot.com',
    measurementId: 'G-6L7Z842GN2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJmx1GcZDCIhZktywLywSs4Q7ysGFqXCw',
    appId: '1:519570864839:android:b51ee7f881019c5c975ce2',
    messagingSenderId: '519570864839',
    projectId: 'brookmate-app-sbu',
    storageBucket: 'brookmate-app-sbu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe8LDbrfZPr9781TarVvXZHNl5iejQRs4',
    appId: '1:519570864839:ios:b90a0e80fdfc5bef975ce2',
    messagingSenderId: '519570864839',
    projectId: 'brookmate-app-sbu',
    storageBucket: 'brookmate-app-sbu.appspot.com',
    iosBundleId: 'com.decompiler.brookmate',
  );
}
